import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";

const poppins = Poppins({
  weight: ["200", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Hero Kidz",
  description: "Generated by hero kidz next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        {/* header */}
        <header>
          <Navbar></Navbar>
        </header>

        {/* main  */}
        <main> {children}</main>

        {/* footer */}
        <footer>
          <Footer></Footer>
        </footer>
      </body>
    </html>
  );
};
export default RootLayout;
