import Products from "@/components/home/Products";
import React from "react";

export const metadata = {
  title: "All Products",
  description: "Generated by hero kidz next app",
};

const ProductsPage = () => {
  return (
    <div>
      <Products></Products>
    </div>
  );
};

export default ProductsPage;
